//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectiveHub.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Directive
    {
        public System.Guid ID { get; set; }
        public byte Status { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Touched { get; set; }
        public string Body { get; set; }
        public Nullable<System.DateTime> DueTime { get; set; }
        public Nullable<System.DateTime> CompletedTime { get; set; }
        public Nullable<int> Priority { get; set; }
    }
}
